[workspace]

members = [
    "curves",
    "scribl",
    "widget",
]

[profile.release]
debug = true

[profile.dev.package.nnnoiseless]
opt-level = 3

# for testing local changes to druid
# [patch."https://github.com/linebender/druid"]
# druid = { path = "../druid/druid", features=["im"] }
