[package]
name = "scribble_curves"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/xi-editor/druid.git" }
serde = { version = "1.0", features = ["derive", "rc"] }
gstreamer = "0.15.4"

[dev-dependencies]
druid-shell = { git = "https://github.com/xi-editor/druid.git" }
piet-common = "0.0.11"
cairo-rs = "0.8.1"
piet-cairo = "0.0.11"
serde_json = "1.0.50"

