# This is an example configuration file for scribl, showing the various options
# and their default settings.

[audio_input]

# Should we automatically remove noise from the incoming audio? This can be overridden
# from within the user interface; this setting just affects the value on start-up.
remove_noise = true

# How aggressively should we remove non-speech sounds? If noise removal is off,
# this has no effect.
#
# A value of 0.0 means that we don't attempt to delete non-speech noises.
# Higher values make us more likely to decide that a particular sound is not
# speech. 1.0 means that we delete everything.
#
# (VAD stands for "voice activity detection.")
vad_threshold = 0.3


[export]

# Height of the exported video, in pixels. (The width is derived from the height
# and the aspect ratio of the animation.)
height = 1080

# The exported video will have this many frames per second.
fps = 30

# The exported video will have (approximately) this bitrate.
bitrate = 4096
