name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: cargo-deps
        name: Cache dependency crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}

      - if: steps.cargo-deps.outputs.cache-hit != 'true'
        name: Fetch dependencies
        run: cargo fetch

  test:
    needs: update-deps
    runs-on: ${{ matrix.os }}
    env:
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]

    name: cargo test
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev
        if: contains(matrix.os, 'ubuntu')

      - name: Install deps
        run: |
            choco install pkgconfiglite
            choco install gstreamer gstreamer-devel
        if: contains(matrix.os, 'windows')

      - name: Restore dependency crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: |
            echo $PKG_CONFIG
            cargo build --locked --verbose
        env:
            PKG_CONFIG: C:/ProgramData/chocolatey/bin/pkg-config.exe
            PKG_CONFIG_PATH: C:/gstreamer/1.0/x86_64/lib/pkgconfig
        if: contains(matrix.os, 'windows')

      - name: Build
        run: cargo build --locked --verbose
        if: contains(matrix.os, 'ubuntu')


      - name: Run tests
        run: cargo test --locked --verbose

